# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: A
  jobs:
    - job: A1
      pool: 
       name: Default
       demand: 
       - Agent.Name -equals CN_A0163
      steps:
        - task: CmdLine@2
          inputs:
             script: dotnet restore \n dotnet run \n